# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        default:
            toolbar: full
            extraPlugins: "autogrow"
            autoGrow_minHeight: 200
            autoGrow_maxHeight: 600
            removeButtons: "PasteFromWord"

