controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

admin_dashboard:
    path: /admin
    controller: App\Controller\DashboardController::index

user_dashboard:
    path: /app_page_index
    controller: App\Controller\PageController::index